#!/bin/bash

# Exit immediately if a command exits with a non-zero status (stop on error)
set -e

# Print each command before executing it (for debugging purposes)
set -x

# Define the build directory
BUILD_DIR="build"

# Default build type is Debug
BUILD_TYPE="Debug"

# Create the build directory if it does not exist
if [ ! -d "$BUILD_DIR" ]; then
  mkdir $BUILD_DIR
fi

# Change into the build directory, saving the previous directory on the stack
pushd $BUILD_DIR

# Install Conan dependencies
conan install .. --output-folder=. --build=missing --settings=build_type=$BUILD_TYPE

# Run CMake to generate the build system in the current directory (build/)
cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1

# Build the project (using the build system generated by CMake)
cmake --build .

# Execute the compiled binary ("virtuniverse" defined in the CMakeLists.txt)
./$BUILD_TYPE/virtuniverse.exe

# Return to the original directory (pop the saved directory from the stack)
popd